### PR TITLE
EAMxx: fix horiz remap bug in case of "sparse" output locations

### LINKED ISSUE #7346: EAMxx: online horizontal remapping appears to shift column index
Thanks to @hassanbeydoun for bringing this to my attention.

The issue arises when using online horizontal interpolation to map onto a subset of columns.  Hassan observed the behavior in a test case using `ne256pg2` and mapping onto the ARM sites using the remap file from the Cess-Potter simulations.  

Using the remap file: `$DIN_LOC_ROOT/atm/scream/maps/20230925_ARM_site_for_Cess_ne256_map.nc` the output data appears to be shifted in the `lat/lon` values.  Quick analysis confirms that the output data has data that matches the source grid column indices shifted by 248010.  In other words if column index 1 was meant to be part of the output instead column index 248011 is output.  Hassan's run and output can be found here: `/pscratch/sd/b/beydoun/e3sm_scratch/pm-gpu/ne256pg2_ne256pg2.F2010-SCREAMv1.Apr30.cess.rainfrac1.sepcldfracs.control/run`

I was able to reproduce this behavior with a `ne30pg2` simulation using the `$DIN_LOC_ROOT/atm/scream/maps/20230925_ARM_site_for_Cess_ne30_map.nc` remap file.  In this case the column indices appear to be shifted by 3382.  See `/pscratch/sd/a/adonahue/e3sm_scratch/pm-gpu/ne30pg2_ne30pg2.F2010-SCREAMv1.May07.2025_master` and `/pscratch/sd/a/adonahue/e3sm_scratch/pm-gpu/ne30pg2_ne30pg2.F2010-SCREAMv1.May07.2025_master.4`. 

The latter case used double the nodes to test if the number of ranks impacted the column shift.  It did not.

### PR DESCRIPTION
**Pull request by bartgol**
Fixes an issue in coarsening remap in case not all the fine grid cols participate to the remap. This bug affected ARM site output.

Fixes #7346 

[BFB]

---

I also changed HommeGridsManager, so that it generates grids with 0-based GIDs rather than 1-based. This is not too important for IO (as the IO layer is already subtracting the grid min GID when computing PIO decomp offsets), but it was making the horiz remapping a bit more brittle.

I will push a unit test for "sampling"-style coarsening remapping soon.

### CODE REVIEW

File: components/eamxx/src/dynamics/homme/interface/dyn_grid_mod.F90 [hunk 1]
```diff
@@ -87,8 +85,9 @@ subroutine get_my_dyn_data (dg_gids, cg_gids, elgpgp, elgids, lat, lon)
       do ip=1,np
         do jp=1,np
           idof = (ie-1)*16+(jp-1)*4+ip
-          cg_gids(idof) = INT(el_cg_gids(ip,jp,ie),kind=c_int)
-          dg_gids(idof) = INT(el_dg_gids(ip,jp,ie),kind=c_int)
+          ! Fortran GIDs are 1-based, but we want 0-based ids
```
Comment (AaronDonahue) [inline components/eamxx/src/dynamics/homme/interface/dyn_grid_mod.F90:88]: Because this touches homme code, we will need to go the regular `next` -> `master` route.  Just noting here since it could be missed at integration.

File: components/eamxx/src/share/grid/remap/horiz_interp_remapper_data.hpp [hunk 2]
```diff
@@ -17,17 +17,21 @@ enum class InterpType {
...
   using view_1d = typename KT::template view_1d<T>;
 
+  // The last argument specifies the base index for gids in the map file
+  // For ncremap-type files, all indices are 1-based
   void build (const std::string& map_file,
               const std::shared_ptr<const AbstractGrid>& fine_grid,
               const ekat::Comm& comm,
-              const InterpType type);
+              const InterpType type,
+              const int map_file_base_gid = 1);
```
Comment (AaronDonahue) [inline components/eamxx/src/share/grid/remap/horiz_interp_remapper_data.hpp:34]: `map_file_base_gid` is default set to 1, I don't see where it could be set to a different value.

File: components/eamxx/src/dynamics/homme/interface/dyn_grid_mod.F90 (hunk 1 above)
Comment (bartgol) [reply components/eamxx/src/dynamics/homme/interface/dyn_grid_mod.F90:88]: This is not Homme, it's still eamxx. It's the _eamxx interface to homme_.

File: components/eamxx/src/share/grid/remap/horiz_interp_remapper_data.hpp (hunk 2 above)
Comment (bartgol) [reply components/eamxx/src/share/grid/remap/horiz_interp_remapper_data.hpp:34]: It's not. I added the hook in case we want to adapt later on. But maybe I'm just better off removing this?

**Comment by bartgol** [comment]
I added a unit test for sparse, sampling-like horiz remapping. To make sure it exercise the correct scenario, I also locally added the test in current master, and verified it fails.

This is good to go.

**Review by AaronDonahue — APPROVED** [review]
This looks great, thanks!  We could also add a remapped output to one of our standalone tests and create an ARM style remap to apply to it.  Then we would catch any changes in DIFF to the baselines...

**Comment by bartgol** [comment]
> This looks great, thanks! We could also add a remapped output to one of our standalone tests and create an ARM style remap to apply to it. Then we would catch any changes in DIFF to the baselines...

I think the unit test `io_horiz_sampling` should already cover that. But I'm not going to say no if someone wants to upgrade standalone (and CIME!) tests...

**Comment by bartgol** [comment]
I am a bit concerned by the diffs in the CIME tests. I see cpl output diffing, which is very unexpected, so I need to dig a bit.

**Comment by AaronDonahue** [comment]
Are the DIFFs related at all to #7322 going in?

**Comment by bartgol** [comment]
> Are the DIFFs related at all to #7322 going in?

Can't be, since that only touches mam4xx compsets, and the diffing ones are the the basic eamxx and dpxx.

**Comment by bartgol** [comment]
Actually, I no longer remember why I needed that change in Homme. Reverting that commit makes everything pass. While I don't understand why that commit should cause the fail, considering that I no longer have a need for that change, I'll just remove it from the PR. I'm quickly testing on mappy one more time before pushing.

**Review by tcclevenger — APPROVED** [review]
