### PR TITLE
Homme: Rework an init routine that was causing a segfault on Chrysalis.

### LINKED ISSUE #4198: Segfault with several PE layouts using RRM v2 config on chrysalis
Using master as of earlier today (Apr 1), I tried using the latest run_e3sm script from @tangq with some modifications of my own to change PE layout.  Several of my attempts fail with the error below.

I tried DEBUG and it doesn't fail (for one layout that was failing).  

```
453: [chr-0444:463739:0:463739] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x21)
453: ==== backtrace (tid: 463739) ====
453:  0 0x0000000000055969 ucs_debug_print_backtrace()  ???:0
453:  1 0x0000000000012b20 .annobin_sigaction.c()  sigaction.c:0
453:  2 0x0000000001bed339 bndry_mod_base_mp_sort_neighbor_buffer_mapping_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/homme/src/share/bndry_mod_base.F90:1011
453:  3 0x0000000001c80d84 prim_driver_base_mp_prim_init1_elem_arrays_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/homme/src/share/prim_driver_base.F90:635
453:  4 0x0000000001c83489 prim_driver_base_mp_prim_init1_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/homme/src/share/prim_driver_base.F90:125
453:  5 0x00000000021fb689 dyn_comp_mp_dyn_init1_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/eam/src/dynamics/se/dyn_comp.F90:149
453:  6 0x0000000001bd0dd7 inital_mp_cam_initial_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/eam/src/dynamics/se/inital.F90:36
453:  7 0x0000000000506ccf cam_comp_mp_cam_init_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/eam/src/control/cam_comp.F90:155
453:  8 0x00000000004ff39d atm_comp_mct_mp_atm_init_mct_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/eam/src/cpl/atm_comp_mct.F90:315
453:  9 0x0000000000441494 component_mod_mp_component_init_cc_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/cime/src/drivers/mct/main/component_mod.F90:257
453: 10 0x000000000042fdee cime_comp_mod_mp_cime_init_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/cime/src/drivers/mct/main/cime_comp_mod.F90:1415
453: 11 0x000000000043e37a MAIN__()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/cime/src/drivers/mct/main/cime_driver.F90:122
453: 12 0x000000000041d622 main()  ???:0

/lcrc/group/e3sm/ac.ndkeen/E3SM_simulations/v2beta3.cmmod023a32x2.5d.wh0.wr
```

Layouts I've tried just to indicate no real pattern, though I haven't seen a fail without threads yet.

```
20 nodes 32x2 OK
23 nodes 32x2 fail
23 nodes 32x2 DEBUG (ran for 2 days until running out of time)
29 nodes 64x1 OK
30 nodes 32x2 fail
32 nodes 32x2 fail
39 nodes 32x2 fail
50 nodes 64x1 OK
50 nodes 32x2 fail
50 nodes 16x4 fail
```

### PR DESCRIPTION
**Pull request by ambrad**
* Modify the v array argument to GhostVunpack_unoriented to remove the
  assumed-size specification. This fixes the issue in one case.
* Turn off optimization in sort_neighbor_buffer_mapping, which fixes the
  rest. Perhaps Intel 19.1.3.304 on Chrysalis with -qopenmp and optimization
  is emitting bad code.
* Rework sort_neighbor_buffer_mapping to remove the automatic arrays of size
  ~nets:nete. Allocating them would also be wasteful.
* Remove the `threadsafe` statements in ghostv(un)pack_unoriented; these are
  not needed because ghost_exchangeVfull already barriers.
* Clean up some large whitespace gaps in edge_mod_base.

Fixes #4198.

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
I ran homme_integration and e3sm_developer on sandiatoss3, with baselines generated from this PR's HEAD~ and get all PASS except for two ELM tests that are staying in the PEND state without showing up in the job queue for some reason:
```
    PEND ERS.f09_g16.I1850ELMCN.sandiatoss3_intel RUN
    PEND ERS.f19_g16.I1850ELM.sandiatoss3_intel.elm-betr RUN
```
These don't use EAM, so whatever mishap occurred has nothing to do with this PR.

**Comment by ambrad** [comment]
We should wait to merge this until @ndkeen gets a chance to see if this PR fixes the issue he observed in his runs. It fixes the reproducer he provided to me.

**Comment by ambrad** [comment]
With the NOOPTIMIZE part of this PR, all PE layouts Noel and I have tried work. The NOOPTIMIZE'ed routine is run once during initialization and is dominated by MPI cost, so the cost of NOOPTIMIZE will be very much in the noise. I'll rerun the integration tests  and report back, probably later this weekend.

**Comment by ambrad** [comment]
Tests pass for the updated PR.

File: components/homme/src/share/bndry_mod_base.F90 [hunk 1]
```diff
@@ -969,97 +977,99 @@ subroutine sort_neighbor_buffer_mapping(par,elem,nets,nete)
   integer :: nets,nete
   type (ghostBuffer3D_t)   :: ghostbuf_cv
 
-  real (kind=real_kind) :: cin(2,2,4,nets:nete)                    ! 1x1 element input data
-  real (kind=real_kind) :: cout(2,2,4,max_neigh_edges+1,nets:nete)   ! 1x1 element output data
+  real (kind=real_kind) :: cin(2,2,4)                      ! 1x1 element input data
+  real (kind=real_kind) :: cout(2,2,4,max_neigh_edges+1)   ! 1x1 element output data
```
Comment (mt5555) [inline components/homme/src/share/bndry_mod_base.F90:981]: at first glance, I was worried about this change because with the edge_pack routines, the element interior data is not packed/unpacked, and thus the output array often needs a nets:nete index to save the interior data.  

but here, it is only edge data - no interior data.  looks like this index was never needed.  good find!

**Review by mt5555 — APPROVED** [review]

**Comment by ambrad** [comment]
@oksanaguba, @mt5555 I'd like this to be merged without a final decision from Noel and others. Whatever is happening is affecting others, and this workaround fixes it without having a downside, so it's reasonable to merge it even though the root cause of #4198 is not known yet.

**Comment by oksanaguba** [comment]
@ambrad what tests did you run?

**Comment by ambrad** [comment]
@oksanaguba I ran homme_integration and e3sm_developer on sandiatoss3.

**Comment by oksanaguba** [comment]
in next
