### PR TITLE
fix topo weights in maint2.1 for proper restart

### LINKED ISSUE #6296: Restart broken in maint2.1 for ELM subgrid.
maint2.1 may fail on restart due to incorrect weights. This is because the topounit weights were never written to or read from restart, which was added later in master.

The simple fix is to insert a `compute_higher_order_weights` call after the subgrid info is read in but prior to evaluating the consistency of the weights. Alternatively, the topounit weights could be added to the restart file, but this could cause fails if running maint2.1 from a restart without those variables.

### PR DESCRIPTION
**Pull request by peterdschwartz**
`lun_pp%wttopounit` is added to the restart file and call to `compute_higher_order_weights` 
is added to the subgridRest module to ensure proper calculation of all weights prior to evaluating them.

Fixes #6296 

[BFB]

### CODE REVIEW

File: components/elm/src/main/subgridRestMod.F90 [hunk 1]
```diff
@@ -476,6 +477,23 @@ subroutine subgridRest_write_and_read(bounds, ncid, flag)
          dim1name='landunit',                                                      &
          long_name='landunit weight relative to corresponding gridcell',           &
          interpinic_flag='skip', readvar=readvar, data=lun_pp%wtgcell)
+        
+    
+    if(flag == 'read') then
```
Comment (bishtgautam) [inline components/elm/src/main/subgridRestMod.F90:482]: Please add a whitespace i.e. `if (flag == 'read') then`

File: components/elm/src/main/subgridRestMod.F90 [hunk 2]
```diff
@@ -476,6 +477,23 @@ subroutine subgridRest_write_and_read(bounds, ncid, flag)
          dim1name='landunit',                                                      &
          long_name='landunit weight relative to corresponding gridcell',           &
          interpinic_flag='skip', readvar=readvar, data=lun_pp%wtgcell)
+        
+    
+    if(flag == 'read') then 
+      ! For backwards compatibility, check if wttopounit is on restart file
+      call check_var(ncid=ncid, varname='land1d_wttopounit', vardesc=vardesc, readvar=readvar)
+      if(readvar) then
```
Comment (bishtgautam) [inline components/elm/src/main/subgridRestMod.F90:485]: Similarly, please add a whitespace.

**Review by bishtgautam — APPROVED** [review]
The PR looks good and I'm requesting a few minor stylistic code changes.

**Comment by rljacob** [comment]
@peterdschwartz can you make the style changes requested so this can get merged?

**Comment by peterdschwartz** [comment]
I made those completely pointless changes

**Comment by rljacob** [comment]
@bishtgautam please merge this.

**Comment by bishtgautam** [comment]
@peterdschwartz, The ELM code has become a stylistic mess and it would be good to make it more of a mess. So, I appreciate you making those pointless changes.

@rljacob The PR has been merged.

**Comment by rljacob** [comment]
This caused some diffs in the maint-2.1 testing.  Please bless.   https://my.cdash.org/viewTest.php?onlyfailed&buildid=2554296

**Comment by peterdschwartz** [comment]
Submitted bless requests. I am surprised to see the diffs as I tested against newly generate baselines for the developer test suite.  Must be something different in the initial condition file for these tests.
