### PR TITLE
Fix negative litter flux bug

### LINKED ISSUE #2538: negative litter fluxes to soil
In some configurations (e.g., C-only) of the land bgc model, litter fluxes to soil are found occasionally to be negative. This is due to the lack of explicit constraint on the transfer fluxes between various litter pools in current code. When this is combined with machine roundoff error, given enough time of model integration, some vegetation pools become negative and then iterate with soil bgc pools and fluxes to amplify the negativity. The current code has some fix in the soil bgc pools to suppress the this positive feedback of negativity, but the root cause associated with litter flux is not addressed. This fix will address the root cause of this bug.

### PR DESCRIPTION
**Pull request by jinyuntang**
Introduced a flux limiter to avoid the occurrence of negative litter fluxes after the phenology 
calculation. Since the default elm is insensitive to these negative litter fluxes, the flux limiter is 
optional, and is off by default, but it can be turned on by setting the logical switch 
use_phenolmter to true. This feature will be essential when the elm big leaf model is 
coupled to plug-in reactive transport models, such as BeTR. The code has passed the 
e3sm_land_developer test suite on cori, and is BFB when the new feature is off.

Fixes #2538 
[BFB]

### CODE REVIEW

**Comment by jinyuntang** [comment]
@bishtgautam, Is there a systematic way to avoid this? I suspect I did not delete some of the spaces, but it occurred anyway.

**Comment by rljacob** [comment]
@jinyuntang Its probably your editor that has a feature which removes them.  You'll need to turn that off.

**Comment by jinyuntang** [comment]
@rljacob , I suspect so. Let me create a new branch and reapply those changes and see how it goes.

**Comment by jinyuntang** [comment]
@bishtgautam, I reapplied the change, and now the unexpected changes are gone. I also redo the e3sm_land_developer test, all went through successfully.

**Comment by bishtgautam** [comment]
Thanks @jinyuntang. I will review it soon.

File: components/clm/src/biogeochem/LSparseMatMod.F90 [hunk 1]
```diff
@@ -0,0 +1,420 @@
...
+    if(errinfo<0)then
+      call endrun(msg='ERROR:: in calc_state_pscal '//errMsg(__FILE__, __LINE__))
+    endif
+    if(lneg .and. it<=itmax)then
+      call lom%calc_reaction_rscal(spm_d%szrow, spm_d%szcol,  pscal, &
+        spm_d,rscal)
+
+      call lom%apply_reaction_rscal(spm_d%szcol, rscal, rfluxes)
+    else
+      exit
```
Comment (bishtgautam) [inline components/clm/src/biogeochem/LSparseMatMod.F90]: Should a warning be printed that the flux correction failed to converge after `itmax` iterations?

File: components/clm/src/biogeochem/LSparseMatMod.F90 [hunk 2]
```diff
@@ -0,0 +1,420 @@
...
+  real(r8) :: pscal(nvars)
+  real(r8) :: d_dt(nvars)
+  real(r8) :: p_dt(nvars)
+  integer :: errinfo
+  type(lom_type) :: lom
+  logical :: lneg
+  integer, parameter :: itmax=40
+  it=0
+  rscal=0._r8
+  do
```
Comment (bishtgautam) [inline components/clm/src/biogeochem/LSparseMatMod.F90]: It is not clear to me the code is doing. Could you add some additional comments?

File: components/clm/src/biogeochem/PhenologyFluxLimitMod.F90 [hunk 3]
```diff
@@ -0,0 +1,1138 @@
...
+  use clm_time_manager            , only : get_step_size
+  use pftvarcon                   , only : npcropmin
+  use clm_varctl                  , only : iulog
+  use abortutils                  , only : endrun
+implicit none
+  private
+#define mov(a,b) a=b
+#define imov(a,b) b=max(a,0._r8)
+#define ascal(a,b) a=a*b
+  integer :: s_cpool
```
[the remark this answers is not in the document]
Comment (bishtgautam) [reply components/clm/src/biogeochem/PhenologyFluxLimitMod.F90]: Additional benefit of creating a base type is that a lot of duplicate code below (e.g. `call spm_list()`, `mov(ystates(s_cpool), veg_cs%cpool(p))`) can be then removed.

[the remark this answers is not in the document]
Comment (jinyuntang) [reply components/clm/src/biogeochem/PhenologyFluxLimitMod.F90]: I have done such back and forth on whether using the base_type and then extend_type vs using this explicit though laborious form. I finally fall to current implementation is just to follow the current practice that is familiar to most people on working the big leaf model. But, I can have a try using your suggested strategy and see if others complain. I will do other suggested changes for sure.

File: components/clm/src/biogeochem/PhenologyFluxLimitMod.F90 [hunk 4]
```diff
@@ -0,0 +1,1138 @@
...
+    ps                    => veg_ps                &
+  )
+
+  ! set time steps
+  dt = real( get_step_size(), r8 )
+  do fp = 1,num_soilp
+    p = filter_soilp(fp)
+    ystates(:) = 0._r8
+    !assemble state variables
+    mov(ystates(s_npool)               , veg_ps%ppool(p))
```
[the remark this answers is not in the document]
Comment (jinyuntang) [reply components/clm/src/biogeochem/PhenologyFluxLimitMod.F90]: For this part, P and N actually using the same set of indices. The n in s_npool (and other similar variables) is meant to be nutrient. Will change it into s_nupool be less confusing?

File: components/clm/src/biogeochem/LSparseMatMod.F90 (hunk 1 above)
Comment (jinyuntang) [reply components/clm/src/biogeochem/LSparseMatMod.F90]: One warning print out is added, although my experience suggests on exiting at maximum iteration, even the answer is still negative, its absolute variable is less than roundoff error and is zeroed off in precision control.

File: components/clm/src/biogeochem/PhenologyFluxLimitMod.F90 (hunk 4 above)
[the remark this answers is not in the document]
Comment (bishtgautam) [reply components/clm/src/biogeochem/PhenologyFluxLimitMod.F90]: In that case, I suggest keep using `s_npool` but add a comment saying that N and P are using the same indices.

**Comment by bishtgautam** [comment]
@jinyuntang, Thanks for the changes. Could you update the title of this PR and the first comment to indicate BFB PR?

File: components/clm/src/biogeochem/PhenologyFluxLimitMod.F90 (hunk 3 above)
[the remark this answers is not in the document]
Comment (jinyuntang) [reply components/clm/src/biogeochem/PhenologyFluxLimitMod.F90]: @bishtgautam, after some further deliberating thinking, I am convinced to keep this part as it is. I have updated other places per your suggestions. Please take another look. Thanks

[the remark this answers is not in the document]
Comment (bishtgautam) [reply components/clm/src/biogeochem/PhenologyFluxLimitMod.F90]: Thanks for considering the suggested change. I'm ok with the current version of this PR>

File: components/clm/src/biogeochem/LSparseMatMod.F90 [hunk 5]
```diff
@@ -0,0 +1,428 @@
...
+  contains
+    procedure :: calc_state_pscal
+    procedure :: calc_reaction_rscal
+    procedure :: apply_reaction_rscal
+  end type lom_type
+  type, public :: sparseMat_type
+    real(r8), pointer :: val(:)      !nonzero val
+    integer , pointer :: icol(:)     !col id for each val
+    integer , pointer :: pB(:)       !first nonzero column id (as in val) in each row
+    integer , pointer :: ncol(:)     !number of nonzero columns in eacho row
```
Comment (bpbond) [inline components/clm/src/biogeochem/LSparseMatMod.F90]: "each"

File: components/clm/src/biogeochem/LSparseMatMod.F90 [hunk 6]
```diff
@@ -0,0 +1,428 @@
...
+  integer :: nrows, szcol
+  integer :: ii,jj,kk
+  logical :: first
+  nrows=size(Amat,1)
+  szcol=size(Amat,2)
+  allocate(spm, source=create_spm_type())
+
+  call spm%init(nelms, nrows, szcol)
+
+  kk = 0
```
Comment (bpbond) [inline components/clm/src/biogeochem/LSparseMatMod.F90]: Seems like a comment here, or at the top of the routine, would be useful to explain why we do this.

File: components/clm/src/biogeochem/LSparseMatMod.F90 [hunk 7]
```diff
@@ -0,0 +1,428 @@
...
+      id=j+spm%pB(i)
+      bmat(i,spm%icol(id))=spm%val(id)
+    enddo
+  enddo
+
+  end subroutine spm_unpack
+
+!---------------------------------------------------------------
+
+  subroutine spm_axpy(nx, ny, a, x, spm, y, errinfo)
```
Comment (bpbond) [inline components/clm/src/biogeochem/LSparseMatMod.F90]: Again, is the function of `spm_axpy` obvious to everyone but me? 😆  A one-line comment explaining the purpose of this would be useful.

File: components/clm/src/biogeochem/LSparseMatMod.F90 [hunk 8]
```diff
@@ -0,0 +1,428 @@
...
+  call spm_list_free(spm_list)
+  end subroutine spm_list_to_mat
+
+
+
+  !-------------------------------------------------------------------------------
+  subroutine calc_state_pscal(this, nprimvars, dtime, ystate, p_dt,  d_dt, pscal, lneg, errinfo)
+    !
+    ! !DESCRIPTION:
+    ! calcualte limiting factor from each primary state variable
```
Comment (bpbond) [inline components/clm/src/biogeochem/LSparseMatMod.F90]: "calculate"

File: components/clm/src/biogeochem/LSparseMatMod.F90 [hunk 9]
```diff
@@ -0,0 +1,428 @@
...
+          pscal(j) = 1._r8
+       endif
+    enddo
+  end subroutine calc_state_pscal
+
+  !-------------------------------------------------------------------------------
+  subroutine calc_reaction_rscal(this, nprimvars, nr, pscal, spm_d, rscal)
+    !
+    ! !DESCRIPTION:
+    ! calcualte limiting factor for each reaction
```
Comment (bpbond) [inline components/clm/src/biogeochem/LSparseMatMod.F90]: ditto

File: components/clm/src/biogeochem/PhenologyFluxLimitMod.F90 [hunk 10]
```diff
@@ -0,0 +1,1161 @@
...
+  call spm_list_insert(spm_list, 1._r8, f_npool_to_grainn_storage        , s_grainn_storage, nelms)
+  call spm_list_insert(spm_list, 1._r8, f_leafn_to_retransn              , s_retransn, nelms)
+  call spm_list_insert(spm_list, 1._r8, f_frootn_to_retransn             , s_retransn, nelms)
+  call spm_list_insert(spm_list, 1._r8, f_livestemn_to_retransn          , s_retransn, nelms)
+  call spm_list_insert(spm_list, 1._r8, f_livecrootn_to_retransn         , s_retransn, nelms)
+
+  call spm_list_to_mat(spm_list, spm_nutrient_p, nelms, f_supplement_to_plantn)
+  end subroutine InitPhenoFluxLimiter
+!---------------------------------------------------------------------------
+  subroutine phenology_flux_limiter(bounds, num_soilc, filter_soilc,&
```
Comment (bpbond) [inline components/clm/src/biogeochem/PhenologyFluxLimitMod.F90]: Here, of all places, there should be some code documentation: what is happening and, crucially, why.

Comment (jinyuntang) [reply components/clm/src/biogeochem/PhenologyFluxLimitMod.F90]: @bpbond, thanks for catching these issues. Now I have added more code comments to make reading the code easier. Please take a revisit.

File: components/clm/src/biogeochem/LSparseMatMod.F90 [hunk 11]
```diff
@@ -0,0 +1,448 @@
...
+  self%icol=icol
+  self%irow=irow
+  nelms=1
+  end subroutine spm_list_init
+!---------------------------------------------------------------
+
+  subroutine spm_list_insert(self, val, icol, irow, nelms)
+  ! 
+  ! DESCRIPTION
+  ! add a specified element to sparse matrix
```
Comment (bpbond) [inline components/clm/src/biogeochem/LSparseMatMod.F90]: 👍

File: components/clm/src/biogeochem/LSparseMatMod.F90 [hunk 12]
```diff
@@ -0,0 +1,448 @@
...
+    real(r8), intent(out) :: pscal(1:nprimvars)
+    logical,  intent(out) :: lneg
+    integer,  intent(out) :: errinfo
+    character(len=betr_errmsg_len) :: msg
+
+    ! !LOCAL VARIABLES:
+    real(r8) :: yt
+    integer  :: j
+    real(r8),parameter :: p_par=0.999_r8
+    real(r8), parameter :: tiny_val=-1.e-14_r8
```
Comment (bishtgautam) [inline components/clm/src/biogeochem/LSparseMatMod.F90]: @jinyuntang, Should the definition of `tiny_val` within this subroutine be omitted because it is also defined for the module at [Line-34](https://github.com/E3SM-Project/E3SM/pull/2946/files#diff-6c09cf12ed23f28ed428bd168b62a143R34)?

Comment (jinyuntang) [reply components/clm/src/biogeochem/LSparseMatMod.F90]: @bishtgautam, Thanks for catching this, I just removed this duplicated line.

**Comment by bishtgautam** [comment]
I forgot to merge this PR earlier and it is now on next.
