### PR TITLE
Fixes hommexx remap bug

### LINKED ISSUE #2711: Propagate vertical remap bugfix to hommexx
The same bug as in #2709 is in hommexx. Someone needs to fix it eventually, not urgent.

### PR DESCRIPTION
**Pull request by bartgol**
Propagates a fix in vertical remap (already present in the Fortran code) to the C++/Kokkos code.

Also: suppressing some compiler warnings (unused/shadowing variables).

Fixes #2711 .

[BFB]

### CODE REVIEW

File: components/clm/src/biogeochem/CNCarbonFluxType.F90 [hunk 1]
```diff
@@ -2008,15 +2008,6 @@ subroutine Summary(this, bounds, num_soilc, filter_soilc, num_soilp, filter_soil
        end do
 
 
-       ! total heterotrophic respiration (HR)
```
Comment (oksanaguba) [inline components/clm/src/biogeochem/CNCarbonFluxType.F90]: it seems this is not a change from this pr; it is probably from some merge, just surprising it appears here.

Comment (bartgol) [reply components/clm/src/biogeochem/CNCarbonFluxType.F90]: I think next is not up to date with master. I rebased the branch on master right before submitting the PR...

Comment (bartgol) [reply components/clm/src/biogeochem/CNCarbonFluxType.F90]: My bad. PRs should be based on master anyways. The integrator will deal with the next/master shenanigans.

File: components/homme/src/share/cxx/PpmRemap.hpp [hunk 2]
```diff
@@ -672,20 +677,46 @@ template <typename boundaries> struct PpmVertRemap : public VertRemapAlg {
...
+    // Initialize lower and upper bounds
+    if (pt_pio(k)>pivot) {
+      lo = 0;
+      hi = k;
+    } else {
+      lo = k;
+      hi = _ppm_consts::PIO_PHYSICAL_LEV-1;
+    }
+
+    // Binary search until hi=lo
```
Comment (ambrad) [inline components/homme/src/share/cxx/PpmRemap.hpp]: Should be "until hi=lo+1".

File: components/homme/src/share/cxx/PpmRemap.hpp [hunk 3]
```diff
@@ -672,20 +677,46 @@ template <typename boundaries> struct PpmVertRemap : public VertRemapAlg {
            sq_coeff * (x2 * x2 * x2 - x1 * x1 * x1) / 3.0;
   }
 
-  ExecViewManaged<Real * [NP][NP][_ppm_consts::DPO_PHYSICAL_LEV]> dpo;
```
Comment (ambrad) [inline components/homme/src/share/cxx/PpmRemap.hpp]: Could include the doc from the Fortran:
```
 ! Find k such that pio(k) <= pivot < pio(k+1). Provide a reasonable input
 ! value for k.
```

File: components/homme/src/share/cxx/PpmRemap.hpp [hunk 4]
```diff
@@ -672,20 +677,46 @@ template <typename boundaries> struct PpmVertRemap : public VertRemapAlg {
...
+    while (hi>lo+1) {
+      k = (lo+hi)/2;
+      if (pt_pio(k)>pivot) {
+        hi = k;
+      } else {
+        lo = k;
+      }
+    }
+    k = lo;
+  }
```
Comment (ambrad) [inline components/homme/src/share/cxx/PpmRemap.hpp]: Could add an NDEBUG-controlled assert here that tests the post-condition asserted in the doc: `pio(k) <= pivot < pio(k+1)`.

**Comment by ambrad** [comment]
There are a lot of formatting changes. Are there actual code changes other than the binary search part?

**Comment by ambrad** [comment]
Did you test this on GPU?

File: components/homme/src/share/cxx/PpmRemap.hpp [hunk 5]
```diff
@@ -296,38 +308,33 @@ template <typename boundaries> struct PpmVertRemap : public VertRemapAlg {
...
       const int kk_cur_lev = k_id(k);
-      assert(kk_cur_lev + 1 >= k);
       assert(kk_cur_lev < parabola_coeffs.extent_int(1));
 
       const Real x2_cur_lev = integral_bounds(k);
       // Repurpose the mass buffer to store the new mass.
       // WARNING: This may not be thread safe in future architectures which
       //          use this level of parallelism!!!
-      mass(k) = compute_mass(
+      mass2 = compute_mass(
```
Comment (ambrad) [inline components/homme/src/share/cxx/PpmRemap.hpp]: I don't think this can work on GPU, in general. mass(k) is being updated in parallel (vector range). So one can't then do `mass1 = mass2`; it's meaningless. mass(k) must be written, and then in a subsequent loop (looks like that loop was erased, but I think it needs to be restored), the mass diff should be computed.

**Comment by ambrad** [comment]
I'd like there to be a unit test for binary_search. This is the Fortran one, although it didn't make it into the Fortran version:
```
  subroutine test_binary_search()
    real(8) :: pio(nlev+2), pin(nlev+1)
    integer :: trial, k, kk
    logical :: ok

    ok = .true.
    !! Run a bunch of random trials.
    do trial = 1, 100000
       !! Generate random pin, pio that satisfy the properties expected of these
       !! coordinate arrays.
       ! Make pio random but sorted.
       call random_number(pio)
       pio(1) = 0
       do k = 2, nlev+1
          pio(k) = pio(k-1) + pio(k)
       end do
       ! Make pin random but sorted.
       call random_number(pin)
       pin(1) = 0
       do k = 2, nlev+1
          pin(k) = pin(k-1) + pin(k)
       end do
       ! Make pio(nlev+1) = pin(nlev+1).
       if (pin(nlev+1) <= pio(nlev+1)) then
          pin(nlev+1) = pio(nlev+1)
       else
          pio(nlev+1) = pin(nlev+1)
       end if
       ! Make pio(nlev+2) > pio(nlev+1).
       pio(nlev+2) = pio(nlev+1) + 1
       !! For each k, run binary search and check that the result maches the
       !! post-condition.
       do k = 1, nlev
          kk = k
          call binary_search(pio, pin(k+1), kk)
          if (kk == nlev+1) kk = nlev
          if ( pio(kk) > pin(k+1) .or. &
               pio(kk+1) < pin(k+1) .or. &
               (pio(kk+1) == pin(k+1) .and. k /= nlev)) then
             print *, 'tbs> failed',k,kk,pio(kk),pio(kk+1),pin(k+1)
             ok = .false.
          end if
       end do
       if (.not. ok) exit
    end do
  end subroutine test_binary_search
```
I can do this in a separate PR at some point if you don't have time to convert it now.

**Comment by bartgol** [comment]
I can add the unit test. I'll move the binary search out of PpmRemap, and test it in the remap_ut tests.

**Comment by bartgol** [comment]
Ok, the last mods are in. Tests pass on GPU and CPU.

**Comment by rljacob** [comment]
Should the C++ version of HOMME have its own integrator?  Mark usually integrates all the HOMME-related PRs.

**Comment by oksanaguba** [comment]
Reassign it to me but I won't do it for another 10-14 days.

File: components/homme/src/share/cxx/PpmRemap.hpp [hunk 6]
```diff
@@ -178,16 +184,21 @@ template <typename boundaries> struct PpmVertRemap : public VertRemapAlg {
...
+      , m_kid("kid", num_elems)
+      , m_ao("a0", get_num_concurrent_teams<ExecSpace>(num_elems * num_remap))
+      , m_mass_o("mass_o",get_num_concurrent_teams<ExecSpace>(num_elems * num_remap))
+      , m_dma("dma", get_num_concurrent_teams<ExecSpace>(num_elems * num_remap))
+      , m_ai("ai", get_num_concurrent_teams<ExecSpace>(num_elems * num_remap))
+      , m_parabola_coeffs("Coefficients for the interpolating parabola",
+            get_num_concurrent_teams<ExecSpace>(num_elems * num_remap))
+  {
+    // Nothing to do here
+  }
```
Comment (rljacob) [inline components/homme/src/share/cxx/PpmRemap.hpp]: These style/indenting changes should go in a separate PR.

Comment (bartgol) [reply components/homme/src/share/cxx/PpmRemap.hpp]: Why is it a problem to have them with this PR? I thought formatting PR were not even a thing in E3SM. Here, I changed the layout cause it was faster (in vim) to do the change and prepend the `m_`, rather than just pre-pending it. Granted, I also think it's way more readable, but if we want to stick with the no-style changes, I can put them back in the order they were before.

Comment (rljacob) [reply components/homme/src/share/cxx/PpmRemap.hpp]: Because if you're looking at diffs to understand how the PR fulfilled its purpose, all this other stuff shows up.  You can do a formatting-only PR if you want.

Comment (bartgol) [reply components/homme/src/share/cxx/PpmRemap.hpp]: Well, this also changed the names of the member variables (to avoid variable shadowing warnings in some functions), so I guess they would show up anyways...

Comment (rljacob) [reply components/homme/src/share/cxx/PpmRemap.hpp]: ok.

**Comment by oksanaguba** [comment]
Do we have hommexx unit tests on any machine? I think not, so this will be bfb then?

**Comment by oksanaguba** [comment]
Ran homme suite on anvil, merged to next.
