### PR TITLE
EAMxx: fix bug in handling of daily/monthly/yearly output files

### LINKED ISSUE #7546: EAMxx: Output not complete when restart period shorter than file_max_storage_type
I set the model to restart every 10 days and want to output daily averages and instantaneous fields for each month to one single history file. 

The restart setup
```
    start_date=2019-08-01
    stop_option=ndays
    stop_n=10
    rest_option=$stop_option
    rest_n=$stop_n
    resubmit=10
```
Output:
- Daily average YAML
```
averaging_type: average
fields:
  physics_pg2:
    field_names:
    - snow_depth_land
file_max_storage_type: one_month
filename_prefix: 1da
iotype: pnetcdf
output_control:
  frequency: 1
  frequency_units: ndays 
```
However, there are only 10 timestamps in `average.2019-08.nc`, and they are even for September, from 2019-09-01 to 2019-09-10. The last output file in this case is `average.2019-11.nc`, which has the date from 2019-11-10 to 2019-11-19. 

Instant output files have different timestamps from the above average output. 
- Daily instant YAML
```
averaging_type: instant
fields:
  physics_pg2:
    field_names:
    - precip_total_surf_mass_flux
file_max_storage_type: one_month
filename_prefix: 1di
iotype: pnetcdf
output_control:
  frequency: 1
  frequency_units: ndays
```
In `instant.2019-08.nc`, it's from 2019-08-22 to 2019-08-31. It seems that the history file is overwritten rather than appended by subsequent restart runs. The last history file is `instant.2019-11.nc`, with timestamp from 2019-11-10 to 2019-11-19.

### PR DESCRIPTION
**Pull request by bartgol**
Fixes tracking of whether the next snapshot will fit in the output file currently open.

[BFB]

---

Fixes #7546

### CODE REVIEW

**Comment by bartgol** [comment]
> The latest commit works well and resolves #7546.
> 
> Would it be possible to automatically modify `restart: force_new_file` to `false` when applying `file_max_storage_type` together with restarting? Or is there another way to prevent overwriting existing output files?
> 
> At the very least, we should note this behavior in the E3SM user guide.

The reason why force_new_file is set to true is b/c of a hang that we were experiencing when resuming to fill the old file. Setting it to false seems wrong, as you would nuke the existing file, with all its content. What I can do is do a check, and error out if it's set to true for daily/monthly/yearly output files, printing an error message explaining what to do: move the old file away, then set force_new_file=true. Would that be enough?

**Comment by meng630** [comment]
Yes, I think adding the check and error out is enough. Btw, the overwriting issue only affects INSTANT streams. @bartgol

**Comment by bartgol** [comment]
> Yes, I think adding the check and error out is enough. Btw, the overwriting issue only affects INSTANT streams. @bartgol

Yes, the bug was for INSTANT streams, but without force_new_file you should overwrite also the AVG streams, no?

**Comment by meng630** [comment]
Yes, both the AVG and INSTANT streams are overwritten if force_new_file=true. My bad.  

> What I can do is do a check, and error out if it's set to true for daily/monthly/yearly output files, printing an error message explaining what to do: move the old file away, then set force_new_file=true. Would that be enough?

Here we should set force_new_file=false, right? I think by default it's true.

@bartgol

**Comment by bartgol** [comment]
Correct.

**Review by meng630 — APPROVED** [review]
Looks great! Thanks a lot! @bartgol

File: components/eamxx/src/share/io/eamxx_output_manager.cpp [hunk 1]
```diff
@@ -250,9 +249,22 @@ setup (const std::shared_ptr<fm_type>& field_mgr,
...
 
       // Check if the prev run wrote any output file (it may have not, if the restart was written
-      // before the 1st output step). If there is a file, check if there's still room in it.
+      // before the 1st output step). If there is a file, we will check if there's still room in it.
       const auto& last_output_filename = scorpio::get_attribute<std::string>(rhist_file,"GLOBAL","last_output_filename");
-      m_resume_output_file = last_output_filename!="" and not restart_pl.get("force_new_file",true);
+      const bool force_new_file = restart_pl.get("force_new_file",true);
+      if (last_output_filename!="" and force_new_file) {
+        auto st = m_output_file_specs.storage.type;
+        // Forcing a new file is dangeour for storage type != NumSnaps, as the filename is likely to clash.
```
Comment (AaronDonahue) [inline components/eamxx/src/share/io/eamxx_output_manager.cpp:257]: "dangerous"

**Review by AaronDonahue — APPROVED** [review]
just a typo in the comments, no need to fix.  Otherwise it looks good.

File: components/eamxx/src/share/io/eamxx_output_manager.cpp (hunk 1 above)
Comment (bartgol) [reply components/eamxx/src/share/io/eamxx_output_manager.cpp:257]: Will fix later then.
