### PR TITLE
Fixes ELM namelist for with active FAN model

### LINKED ISSUE #6152: ELM FAN test broken
@rljacob's comment https://github.com/E3SM-Project/E3SM/pull/6142#issuecomment-1894481428

>I merged this to master without realizing it made namelist changes (wasn't labeled. Fixed). And one of those namelist changes was wrong. This PR turns off FAN for the FAN test:

```
SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.chrysalis_intel.elm-fan NML DIFF:
Comparison failed between '/lcrc/group/e3sm2/e3smtest/scratch/chrys/J/SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.chrysalis_intel.elm-fan.C.JMasterIntegration20240115_035742/CaseDocs/lnd_in' with '/lcrc/group/e3sm2/baselines/chrys/intel/master/SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.chrysalis_intel.elm-fan/CaseDocs/lnd_in'
Missing namelist: fan_nml
```

### PR DESCRIPTION
**Pull request by bishtgautam**
If `use_fan = .true.` in `user_nl_elm`, add settings for the FAN model in `lnd_in`.

Fixes #6152 
[BFB]

### CODE REVIEW

File: components/elm/bld/ELMBuildNamelist.pm [hunk 1]
```diff
@@ -3021,7 +3023,9 @@ sub setup_logic_fan {
             fatal_error('Cannot use_fan if use_crop is false');
           }   #
 
-          if( $nl_flags->{'use_fan'} eq ".true." ) {
+	  my $var = "use_fan";
+	  my $val = $nl->get_value($var);
+          if( $val eq ".true." ) {
```
Comment (rljacob) [inline components/elm/bld/ELMBuildNamelist.pm:3028]: So it was a perl error?

Comment (bishtgautam) [reply components/elm/bld/ELMBuildNamelist.pm:3028]: Yes. The information about `use_fan` was being extracted from the wrong data structure.

**Review by bbye — APPROVED** [review]

**Comment by rljacob** [comment]
Will this change namelists for the fan test?

**Comment by rljacob** [comment]
use_fan = .true. now shows up in the elm-fan test.  And that test passes.
