### PR TITLE
EAMxx: change handling of timestamp inside atm proc

### LINKED ISSUE #7074: EAMxx: Incorrect Time Step Values in Sub-Stepped Processes Using timestamp().get_num_steps()
I’m attempting to print the model time step in the run_impl method of an atmosphere process using `auto ts = timestamp().get_num_steps();`. This approach works correctly when I use it in a process that isn’t sub-stepped, such as `rrtmgp`, where I get the expected time step value. However, when I use the same method in processes that are sub-stepped (e.g., P3 or SHOC), the returned time step values are incorrect—they differ from the time step values logged in the atm.log.* file.

### PR DESCRIPTION
**Pull request by bartgol**
* Update timestamp inside subcycle loop
* Update timestamp before calling run_impl

[non-BFB for eamxx-standalone testing and mam4xx cases only]

Fixes #7074

---

The impact of the PR is twofolds:

1. Processes that are subcycled will see the content of the timestamp returned by `timestamp()` changing between iterations. Before, the base class was updating `m_time_stamp` only after all the subcycles iterations.
2. Instead of returning the time "right before the call to run_impl", the method now returns the time that run_impl is supposed to advance to. In other words, it returns the "end-of-step" time. That's b/c the vast majority of calls to `timestamp()` where interested in the end-of-step time, which forced the calling site to do something like `auto ts = timestamp() + dt;`.

The second change can have a few side effects, as there were a few places inside derived classes where we would call `timestamp()` inside `run_impl` _without_ adding dt. I'll list them here, along with folks who I'd like to review whether the new behavior is ok. If the new behavior is NOT ok (that is, you'd like those calls to `timestamp()` to return the "start-of-step" timestamp (as before), let me know, and I can add a "start-of-step" timestamp getter and use it in your class.

- rrtmgp: the timestamp was used to determine whether this was a rad step (in case of supercycling) as well as to determine the orb parameters. @brhillman 
- iop_forcing: the timestamp was used to read iop file data. It is possible that IOPDataManager was taking care of the fact that timestamp was the "start-of-step", while searching for the iop file time slice. In that case, we can either modify IOPDataManager search logic, or as said above, we can add a "start-of-step" timestamp getter. @tcclevenger 
- ml_correction: the timestamp was used to create the timestamp string, to pass to the ml emulator. I am not familiar with this, but I also think nobody is using this ML, so maybe it's not worth checking if things work as expected? @AaronDonahue 
- mam: the timestamp was used in a few places, in code that does a manual data interpolation (the code was likely copy+pasted and adapted from the old impl of SPA). I feel like using the "end-of-step" data is more appropriate, but I am not entirely sure. There's also an odd timestamp treatment that I will point out in the changes tab. @singhbalwinder 
- sc importer: this is probably the same situation as iop_forcing, as the timestamp is used when calling `overwrite_iop_imports`. @tcclevenger 
- homme dynamics: besides a few places that are only used during init, there was one place where we called timestamp(), and it turns out that what we do now is more appropriate (long story).

### CODE REVIEW

File: components/eamxx/src/physics/mam/eamxx_mam_microphysics_process_interface.cpp [hunk 1]
```diff
@@ -660,7 +659,6 @@ void MAMMicrophysics::run_impl(const double dt) {
   // Note: We are following the RRTMGP EAMxx interface to compute the zenith
   // angle. This operation is performed on the host because the routine
   // shr_orb_cosz_c2f has not been ported to C++.
-  auto ts2          = timestamp();
```
Comment (bartgol) [inline components/eamxx/src/physics/mam/eamxx_mam_microphysics_process_interface.cpp:663]: @singhbalwinder I was puzzled by the `ts2` variable. Then I came to the conclusion that you are likely using ts2 (rather than the ts above) so that you do exactly what RRTMGP does, right? If that's the case, I will decide what to do with this mod (whether to keep it or roll it back) depending on what Ben says regarding the change of ts handling in rrtmgp.

Comment (singhbalwinder) [reply components/eamxx/src/physics/mam/eamxx_mam_microphysics_process_interface.cpp:663]: Yes, you are right. @odiazib added this code to mimic RRTMGP. We likely used `ts2` as `ts` was declared above and held a different value. It would be nice to unify these to avoid confusion.

**Comment by AaronDonahue** [comment]
>ml_correction: the timestamp was used to create the timestamp string, to pass to the ml emulator. I am not familiar with this, but I also think nobody is using this ML, so maybe it's not worth checking if things work as expected? @AaronDonahue

@bartgol , you are correct that no one is using ML right now.  I believe that the timestamp here is being used for the time/date of the current timestep.  I see two options, 
1) if we do create a start_of_step getter than we can use it here.
2) otherwise, add a comment explaining that this is the "end of the step" date/time.  That way if someone revives this effort they are not gotten by this distinction.

**Comment by singhbalwinder** [comment]
As you know, for MAM4xx, we followed the SPA file reader. It will be good to be consistent with the SPA reader as the files that we are reading are very similar to SPA.

**Comment by bartgol** [comment]
I decided to rework the branch. I will leave some comments on the code now.

File: components/eamxx/docs/_presentations_srcs/eamxx-tutorial-2025-part2.md [hunk 2]
```diff
@@ -487,7 +487,7 @@ void POMPEI::run_impl(const double dt) {
   using PC = scream::physics::Constants<Real>;
   auto g   = PC::gravit;
 
-  auto t    = timestamp() + dt;
```
Comment (bartgol) [inline components/eamxx/docs/_presentations_srcs/eamxx-tutorial-2025-part2.md:490]: @mahf708 Even though _at the time of the tutorial_ `timestamp()` was correct, I decided to change this, for the sake of who comes later and reads the docs.

File: components/eamxx/src/dynamics/homme/eamxx_homme_fv_phys.cpp [hunk 3]
```diff
@@ -304,7 +304,7 @@ void HommeDynamics::fv_phys_rrtmgp_active_gases_remap (const RunType run_type) {
         gfr.remap_tracer_dyn_to_fv_phys(time_idx, 1, in_dgll, out_phys);
         Kokkos::fence();
 
-        f_phys.get_header().get_tracking().update_time_stamp(timestamp());
+        f_phys.get_header().get_tracking().update_time_stamp(start_of_step_ts());
```
Comment (bartgol) [inline components/eamxx/src/dynamics/homme/eamxx_homme_fv_phys.cpp:307]: This is only run at init, where start/end of step are the same.

File: components/eamxx/src/physics/iop_forcing/eamxx_iop_forcing_process_interface.cpp [hunk 4]
```diff
@@ -346,7 +346,8 @@ void IOPForcing::run_impl (const double dt)
   const auto Q = get_group_out("tracers").m_monolithic_field->get_view<Pack***>();
 
   // Load data from IOP files, if necessary
-  m_iop_data_manager->read_iop_file_data(timestamp());
+  // TODO: this is using the TS from the beg of the step. Should it use end_of_step_ts() instead?
+  m_iop_data_manager->read_iop_file_data(start_of_step_ts());
```
Comment (bartgol) [inline components/eamxx/src/physics/iop_forcing/eamxx_iop_forcing_process_interface.cpp:350]: @tcclevenger same comment here: i left as is, but you may want to think about this, and see if it's worth changing.

File: components/eamxx/src/physics/mam/eamxx_mam_microphysics_process_interface.cpp [hunk 5]
```diff
@@ -457,7 +457,7 @@ void MAMMicrophysics::initialize_impl(const RunType run_type) {
     auto linoz_cariolle_pscs =
         buffer_.scratch[7];  // Cariolle parameter for PSC loss of ozone [1/s]
 
-    auto ts = timestamp();
+    auto ts = start_of_step_ts();
```
Comment (bartgol) [inline components/eamxx/src/physics/mam/eamxx_mam_microphysics_process_interface.cpp:460]: @singhbalwinder I left all use of timestamp _mostly_ unchanged in mam. Meaning that I am using `start_of_step_ts` (rather than `end_of_step_ts`), but since timestamps are updated _within subcycled processes_ this is not 100% equivalent to what was done before. Hence, the non-bfbness.

But you may want to investigate whether we should switch all of these to `end_of_step_ts`.

File: components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp [hunk 6]
```diff
@@ -806,7 +806,7 @@ void RRTMGPRadiation::run_impl (const double dt) {
   const auto do_aerosol_rad = m_do_aerosol_rad;
 
   // Are we going to update fluxes and heating this step?
-  auto ts = timestamp();
+  auto ts = end_of_step_ts();
```
Comment (bartgol) [inline components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp:809]: @brhillman I changed this, since it seemed wrong that RRTMGP used the timestamp at the beginning of this step down below, where orb params are used. However, with this mod, we also change _when_ rad runs. E.g., with rad freq 2, rad would run
- before this change: on steps 1, 3, 5, ..
- after this change: on steps 2, 4, 6, ...

Not sure if this is ok.

File: components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp [hunk 7]
```diff
@@ -99,7 +99,7 @@ void MLCorrection::initialize_impl(const RunType /* run_type */) {
 // =========================================================================================
 void MLCorrection::run_impl(const double dt) {
   // use model time to infer solar zenith angle for the ML prediction
-  auto current_ts = timestamp();
+  auto current_ts = start_of_step_ts();
```
Comment (bartgol) [inline components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp:102]: @AaronDonahue I did not change this, also b/c I don't know who still uses MLCorrection. That said, it seems wrong that ML uses the timestamp at the _beginning_ of the step. If you think it should switch, I can change this.

**Review by tcclevenger — APPROVED** [review]

**Comment by bartgol** [comment]
The eamxx-sa failures are all related to the p3_bfbhash comparison, which is expected, since the p3-pst sha is now printing with the timestamp _after_ the subcycle iteration (before, the timestamp was not updated until _after_ all subcycling was over).

File: components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp (hunk 7 above)
Comment (AaronDonahue) [reply components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp:102]: I think this is okay for now.  We are not actively using MLCorrection so we won't break anything.  If you do have to make another commit maybe you could add a comment to this line saying exactly what you say above, that this means the CorrectiveML is using the time at the beginning of the timestep, but if not I think we will be alright.

Comment (bartgol) [reply components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp:102]: No other commit planned. I will integrate as is, as soon as approved, unless changes are requested.

**Review by singhbalwinder — APPROVED** [review]
Looks good. Thanks, @bartgol !

File: components/eamxx/src/physics/mam/eamxx_mam_microphysics_process_interface.cpp (hunk 5 above)
Comment (bartgol) [reply components/eamxx/src/physics/mam/eamxx_mam_microphysics_process_interface.cpp:460]: I just noticed this fcn is inside `initialize_impl`, where start/end of timestep have same timestamp.
