### PR TITLE
 Fix a bug in coupling between zm microphys/hetfrz ice nucleation and mam aerosol

### LINKED ISSUE #7353: EAM: bugs in coupling between zm microphys and mam aerosol and in coupling between hetfrz ice nucleation and mam aerosol
In [zm_microphys.F90](https://github.com/E3SM-Project/E3SM/blob/master/components/eam/src/physics/cam/zm_microphysics.F90) 

The calculation of dust number for ice nucleation does not account other aerosol species (so4, bc, pom, soa, mom).

https://github.com/E3SM-Project/E3SM/blob/master/components/eam/src/physics/cam/zm_microphysics.F90#L2027C1-L2056C27

```
                !For modal aerosols, assume for the upper troposphere:
                ! soot = accumulation mode
                ! sulfate = aiken mode
                ! dust = coarse mode
                ! since modal has internal mixtures.
                soot_num = 0.5_r8*(aero%numg_a(i,k-1,aero%mode_accum_idx)             &
                                  +aero%numg_a(i,k,aero%mode_accum_idx))*rho(i,k)*1.0e-6_r8
                dmc  = 0.5_r8*(aero%mmrg_a(i,k-1,aero%coarse_dust_idx,aero%mode_coarse_idx)      &
                              +aero%mmrg_a(i,k,aero%coarse_dust_idx,aero%mode_coarse_idx))
                ssmc = 0.5_r8*(aero%mmrg_a(i,k-1,aero%coarse_nacl_idx,aero%mode_coarse_idx)      &
                              +aero%mmrg_a(i,k,aero%coarse_nacl_idx,aero%mode_coarse_idx))
                if (dmc > 0._r8) then
                    dst_num = dmc/(ssmc + dmc) *(aero%numg_a(i,k-1,aero%mode_coarse_idx)         &
                              + aero%numg_a(i,k,aero%mode_coarse_idx))*0.5_r8*rho(i,k)*1.0e-6_r8
                else
                   dst_num = 0.0_r8
                end if
```

In [hetfrz_classnuc_cam.F90](https://github.com/E3SM-Project/E3SM/blob/master/components/eam/src/physics/cam/hetfrz_classnuc_cam.F90)

One place in calculation misses MAM5 compilation flag.

https://github.com/E3SM-Project/E3SM/blob/master/components/eam/src/physics/cam/hetfrz_classnuc_cam.F90#L1619C4-L1638C11

```

      if (awcam(3) > 0._r8) then
#if (defined MODAL_AERO_4MODE_MOM && defined RAIN_EVAP_TO_COARSE_AERO )
         awfacm(3) = ( aer(ii,kk,bc_coarse) + aer(ii,kk,soa_coarse) + &
                       aer(ii,kk,pom_coarse) + aer(ii,kk,mom_coarse) )/ &
                     ( aer(ii,kk,soa_coarse) + aer(ii,kk,pom_coarse) + &
                       aer(ii,kk,so4_coarse) + aer(ii,kk,bc_coarse) + aer(ii,kk,mom_coarse) )
#elif (defined MODAL_AERO_4MODE_MOM)
         awfacm(3) = ( aer(ii,kk,mom_coarse) ) / &
                     ( aer(ii,kk,so4_coarse) + aer(ii,kk,mom_coarse) )
#elif (defined RAIN_EVAP_TO_COARSE_AERO) 
         awfacm(3) = ( aer(ii,kk,bc_coarse) + aer(ii,kk,soa_coarse) + &
                       aer(ii,kk,pom_coarse) )/ &
                     ( aer(ii,kk,soa_coarse) + aer(ii,kk,pom_coarse) + &
                       aer(ii,kk,so4_coarse) + aer(ii,kk,bc_coarse) )
#else
         awfacm(3) = 0._r8
#endif
   else
         awfacm(3) = 0._r8
   end if

```

### PR DESCRIPTION
**Pull request by mingxuanwupnnl**
This PR fixes a bug in coupling between zm microphys and mam aerosol 
and a bug in coupling between heterogeneous ice nucleation and mam aerosol. 

There are minimal changes between two 10yr F2010 runs.

Fixes #7353. 

[non-BFB]

--------------------------------------
model vs obs
[CNTL](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.mwu/E3SMv3/20250522.v3.LR.F2010.CNTL.PD.chrysalis/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0002-0011/viewer/index.html)
[ZM Microphys bug fix](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.mwu/E3SMv3/20250526.v3.LR.F2010.ZMMicrophys_bugfix.PD.chrysalis/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0002-0011/viewer/index.html)

model vs model
[ZM Microphys bug fix vs CNTL](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.mwu/E3SMv3/20250526.v3.LR.F2010.ZMMicrophys_bugfix.PD.chrysalis/e3sm_diags/atm_monthly_180x360_aave_mvm/model_vs_model_0002-0011/viewer/index.html)

[IICE results](https://portal.nersc.gov/project/m2136/bin/iice/iice.cgi?url1=https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.mwu/E3SMv3/20250522.v3.LR.F2010.CNTL.PD.chrysalis/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0002-0011/viewer&label1=CNTL&url2=https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.mwu/E3SMv3/20250526.v3.LR.F2010.ZMMicrophys_bugfix.PD.chrysalis/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0002-0011/viewer&label2=ZMmicro%20bug%20fix&category=&plot=&diff=0&dconfig=vsObs&)

atm_nbfb tests suggest the model with the changes introduced still produces statistically identical results with respect to the baselines.

-  [MVK test](https://web.lcrc.anl.gov/public/e3sm/ac.wlin/evv/MVK_PS.ne4pg2_oQU480.F2010.chrysalis_intel.C.20250601_105918_12toly/)
- [PGN test](https://web.lcrc.anl.gov/public/e3sm/ac.wlin/evv/PGN_P1x1.ne4pg2_oQU480.F2010.chrysalis_intel.C.20250529_121927_axld0g/)
- [TSC test](https://web.lcrc.anl.gov/public/e3sm/ac.wlin/evv/TSC_PS.ne4pg2_oQU480.F2010.chrysalis_intel.C.20250529_121927_axld0g/)

### CODE REVIEW

**Review by hwangacme — APPROVED** [review]

**Comment by whannah1** [comment]
These changes are going to cause conflicts with my current ZM refactoring - Why was I not added as a reviewer?!?! I need to think about the order that these changes are made to minimize the conflicts.

Is this something critical for v3HR?

**Comment by mingxuanwupnnl** [comment]
> These changes are going to cause conflicts with my current ZM refactoring - you should have added me as a reviewer! I need to think about the order that these changes are made to minimize the conflicts.
> 
> Is this something critical for v3HR?

Hi Walter, just added you as a reviewer. I thought the refactor is for ZM convection. This bug was identified a while ago and should not be climate changing.

**Comment by whannah1** [comment]
> Hi Walter, just added you as a reviewer. I thought the refactor is for ZM convection. This bug was identified a while ago and should not be climate changing.

Thanks.

The ZM refactor encompasses "all" of ZM because we ideally want to port all of it to C++, which requires breaking up the code into smaller chunks. The ZM microphysics is one of the biggest offenders in this respect, but we don't want the actual MG based scheme since we're [ideally] going to use P3 in the EAMxx version of ZM. So we will likely just port the "framework" of the ZM microphysics, which still will require a large refactoring effort (which we haven't gotten to yet).

The branche that this will conflict with is still a work in progress and needs to wait for other PRs to be merged so I can rebase. After thinking about this some more, I think I can manage the conflicts as they arise - so I'm ok having this merged first.

**Comment by bpbond** [comment]
Adding @njeffery to assess any implications for the HES ocean simulations

**Comment by DJFJJA** [comment]
**zm_microphysics.F90**
Lines 2061-2069
 
image

**1.	The logic is missing a branch for the following case:**
•	MODAL_AERO_5MODE is defined
•	RAIN_EVAP_TO_COARSE_AERO is not defined
•	MODAL_AERO_4MODE_MOM is not defined
In this situation, the logic falls through to the #else clause, where only ssmc and dmc are considered. However, the presence of MODAL_AERO_5MODE implies that mommc should also be included in the calculation. You may need to add a specific #elif for MODAL_AERO_5MODE.

**2.	Could you explain why** wght = dmc / (ssmc + dmc) **is used in line 2068, instead of** wght = dmc / (ssmc + dmc + so4mc)?

**Review by DJFJJA — CHANGES_REQUESTED** [review]
**zm_microphysics.F90**
Lines 2061-2069
image

**1. The logic is missing a branch for the following case:**
• MODAL_AERO_5MODE is defined
• RAIN_EVAP_TO_COARSE_AERO is not defined
• MODAL_AERO_4MODE_MOM is not defined
In this situation, the logic falls through to the #else clause, where only ssmc and dmc are considered. However, the presence of MODAL_AERO_5MODE implies that mommc should also be included in the calculation. You may need to add a specific #elif for MODAL_AERO_5MODE.

**2. Could you explain why** wght = dmc / (ssmc + dmc) **is used in line 2068, instead of** wght = dmc / (ssmc + dmc + so4mc)?

**Comment by mingxuanwupnnl** [comment]
@DJFJJA Thank you for reviewing the code changes. I revised the code to include MODAL_AERO_5MODE. I set `` wght = dmc/(ssmc + dmc)`` just to be consistent with old zm microphys code. By default, the code should choose the first condition.

```

                    if (dmc > 0._r8) then
#if ( ( defined MODAL_AERO_4MODE_MOM || defined MODAL_AERO_5MODE ) && ( defined RAIN_EVAP_TO_COARSE_AERO ) )
                       wght = dmc/(ssmc + dmc + so4mc + bcmc + pommc + soamc + mommc)
#elif ( defined MODAL_AERO_4MODE_MOM || defined MODAL_AERO_5MODE )
                       wght = dmc/(ssmc + dmc + so4mc + mommc)
#elif (defined RAIN_EVAP_TO_COARSE_AERO)
                       wght = dmc/(ssmc + dmc + so4mc + bcmc + pommc + soamc)
#else
                       wght = dmc/(ssmc + dmc + so4mc)
#endif


```

**Review by DJFJJA — APPROVED** [review]

**Comment by xuezhengllnl** [comment]
> This PR fixes a bug (issue #7353 ) in coupling between zm microphys and mam aerosol and a bug in coupling between heterogeneous ice nucleation and mam aerosol.
> 
> There are minimal changes between two 10yr F2010 runs.
> 
> [CNTL](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.mwu/E3SMv3/20250522.v3.LR.F2010.CNTL.PD.chrysalis/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0002-0011/viewer/index.html) [ZM Microphys bug fix](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.mwu/E3SMv3/20250526.v3.LR.F2010.ZMMicrophys_bugfix.PD.chrysalis/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0002-0011/viewer/index.html)
> 
> [IICE results](https://portal.nersc.gov/project/m2136/bin/iice/iice.cgi?url1=https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.mwu/E3SMv3/20250522.v3.LR.F2010.CNTL.PD.chrysalis/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0002-0011/viewer&label1=CNTL&url2=https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.mwu/E3SMv3/20250526.v3.LR.F2010.ZMMicrophys_bugfix.PD.chrysalis/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0002-0011/viewer&label2=ZMmicro%20bug%20fix&category=&plot=&diff=0&dconfig=vsObs&)

Hi Mingxuan, 
Did you estimate the change in ERFaero with the bug fixes? Thanks,
-Xue

**Comment by mingxuanwupnnl** [comment]
Hi @xuezhengllnl Thank you. I would also expect minimal changes in ERFaer. As you can see from the E3SM diags, there are minimal changes in aerosol budget between the two runs.

File: components/eam/src/physics/cam/hetfrz_classnuc_cam.F90 [hunk 1]
```diff
@@ -1617,7 +1617,7 @@ subroutine get_aer_num(ii, kk, ncnst, aer, aer_cb, rhoair,&
       end if
 
       if (awcam(3) > 0._r8) then
-#if (defined MODAL_AERO_4MODE_MOM && defined RAIN_EVAP_TO_COARSE_AERO )
+#if ( (defined MODAL_AERO_4MODE_MOM || defined MODAL_AERO_5MODE) && defined RAIN_EVAP_TO_COARSE_AERO )
```
Comment (xuezhengllnl) [inline components/eam/src/physics/cam/hetfrz_classnuc_cam.F90:1620]: @mingxuanwupnnl do you want to change line 1625 #elif (defined MODAL_AERO_4MODE_MOM) to #elif (defined MODAL_AERO_4MODE_MOM || defined MODAL_AERO_5MODE) ? Otherwise, MODAL_AERO_5MODE without RAIN_EVAP_TO_COARSE_AERO would be #else

**Comment by xuezhengllnl** [comment]
> Hi @xuezhengllnl Thank you. I would also expect minimal changes in ERFaer. As you can see from the E3SM diags, there are minimal changes in aerosol budget between the two runs.

Hi @mingxuanwupnnl, 

I went through the changes and left a minor comment shown above. I’m not very familiar with the aerosol variables in MODAL_AERO_4MODE_MOM and MODAL_AERO_5MODE, so please review hetfrz_classnuc_cam.F90 to ensure that all conditionals might related to MODAL_AERO_5MODE are correct (e.g., Line 1308, Line 1625 in the subroutine get_aer_num).

As I understand it, your ZM microphysics changes will initially reduce (through wght) the dust number available for ZM ice nucleation, but the added contact nucleation coefficient (tcnst) then scales the nucleated numbers back up, resulting in a small net change. Since the primary impact is on ZM ice clouds, we just need to confirm that the aerosol indirect effect on ice clouds isn’t significantly altered. Thanks,

File: components/eam/src/physics/cam/hetfrz_classnuc_cam.F90 (hunk 1 above)
Comment (mingxuanwupnnl) [reply components/eam/src/physics/cam/hetfrz_classnuc_cam.F90:1620]: @xuezhengllnl Thank you. I added MODAL_AERO_5MODE for places where there is only MODAL_AERO_4MODE_MOM. Note that both MODAL_AERO_5MODE and RAIN_EVAP_TO_COARSE_AERO are always on by default for v3.

**Comment by rljacob** [comment]
@njeffery please approve

**Review by crterai — APPROVED** [review]
Thank you, @mingxuanwupnnl. The changes in RESTOM indeed look more like noise rather than something systematic.

**Comment by rljacob** [comment]
@njeffery nevermind.  This has been shown to be non climate changing.

**Comment by wlin7** [comment]
Merged to next.

**Comment by rljacob** [comment]
This does seem to have affected the MVK test.  next with hash 03aa268b, it was passing.  It showed a diff with 6ebccbbfd which included this PR and #7395 
https://web.lcrc.anl.gov/public/e3sm/e3smtest/evv/MVK_PS.ne4pg2_oQU480.F2010.chrysalis_intel.C.JNextNbfb20250603_010343/index.html
