### PR TITLE
Fixes for FATES-HYDRO model

### LINKED ISSUE #2346: Dimension mismatch bug between soil water uptake arrays from FATES HYDRO to ELM
There is a dimension mismatch bug when passing qflx_soil2root_sisl from FATES to qflx_rootsoi_col in E3SM land model within clmfates_interface Mod.  Specifically, it is related to the following line of code:

waterflux_inst%qflx_rootsoi_col(c,:) = this%fates(nc)%bc_out(s)%qflx_soil2root_sisl(:)

qflx_rootsoil_col has a dimension of nlevgrnd while qflx_soil2root_sisl has a dimension of nlevsoi. nlevgrnd includes lower layers that are hydrologically inactive. As the FATES hydro only consider the root water uptake in the soil, we suggest only pass the soil water uptake to the qflx_rootsoi_col in ELM.

### PR DESCRIPTION
**Pull request by xuchongang**
This pull request updates the following:
1. Fixes the dimension mismatch bug when coupling ELM to FATES-HYDRO 
2. Updates the initial soil water content for FATES-HYDRO; and 
3. Returns to ELM the water stored in the plant when FATES-HYDRO is active

Fixes #2346 

[BFB]

### CODE REVIEW

File: components/clm/src/biogeophys/WaterStateType.F90 [hunk 1]
```diff
@@ -670,7 +670,7 @@ subroutine InitCold(this, bounds, &
                   if (j > nlevbed) then
                      this%h2osoi_vol_col(c,j) = 0.0_r8
                   else
-                     this%h2osoi_vol_col(c,j) = 0.15_r8
+                     this%h2osoi_vol_col(c,j) = 0.70*watsat_col(c,j)  !0.15_r8 to avoid very dry conditions that cause errors in FATES HYDRO
```
Comment (bishtgautam) [inline components/clm/src/biogeophys/WaterStateType.F90]: I suggest initializating soil moisture to a different value only when FATES HYDRO is active via:

```
if (use_fates_planthydro) then
   this%h2osoi_vol_col(c,j) = 0.70_r8*watsat_col(c,j) 
else
   this%h2osoi_vol_col(c,j) = 0.15_r8
endif
```

**Comment by xuchongang** [comment]
@rljacob and @bishtgautam , I have resolved all your review suggestions. Specifically, I have removed my last commit and rebased to the master instead of merging from master. I have opened an issue (2346 to record the bug). I have also made the suggested changes by Gautam. Please let me know if you have further concerns.

**Comment by bishtgautam** [comment]
@xuchongang, Thanks for the changes. I have updated the first comment to follow [E3SM's template](https://acme-climate.atlassian.net/wiki/spaces/Docs/pages/16253965/Commit+message+template).
