### PR TITLE
Generate a meaningful error msg when endrun called with no parameters

### LINKED ISSUE #2498: calling endrun in CAM can cause misleading error reporting
In phys_grid.F90 there are two general ways that endrun is called, e.g. 

       if (pcols < maxblksiz) then
          write(iulog,*) 'pcols = ',pcols, ' maxblksiz=',maxblksiz
          call endrun ('PHYS_GRID_INIT error: phys_loadbalance -1 specified but PCOLS < MAXBLKSIZ')
       endif

and

         else
            if (masterproc) then
               write(iulog,*) "PHYS_GRID_INIT error: opt", opt, "specified, ", &
                  "but could not divide processes into pairs."
            endif
            call endrun()
         endif

endrun is just a renamed version of shr_abort_abort.

     module cam_abortutils
       use shr_sys_mod, only: endrun => shr_sys_abort
       implicit none
       private
       save
       public :: endrun
     end module cam_abortutils

and

     MODULE shr_sys_mod
     ...
        use shr_abort_mod, only: shr_sys_abort => shr_abort_abort

When called in the second fashion, a meaningful message is written to atm.log by masterproc, but then shr_abort_abort prints out nprocs-1 copies of the following to e3sm.log and one copy to atm.log:

      ERROR: Unknown error submitted to shr_abort_abort.

It is probably worthwhile going through and adding real error messages to the endrun calls (at a minimum). However, a single error message is probably preferred are well? Not sure what the design should be, but it took me awhile to think to look in atm.log to find the real error message in atm.log after seeing all of the "Unknown error" messages in e3sm.log .

Asking both Balwinder (for phys_grid) and Rob (for shr_abort_abort in CIME) to think about this and reassign as appropriate (and it you think that this is worth addressing).

### PR DESCRIPTION
**Pull request by worleyph**
There are two general ways that endrun is called in CAM, one with a
string argument that describes the error causing the abort and one
without any parameters, but with an explicit write describing
the error that precedes the call to endrun. Examples of the two are as follows.

     if (pcols < maxblksiz) then
        write(iulog,*) 'pcols = ',pcols, ' maxblksiz=',maxblksiz
        call endrun ('PHYS_GRID_INIT error: phys_loadbalance -1 specified but PCOLS < MAXBLKSIZ')
     endif

and

     else
        if (masterproc) then
           write(iulog,*) "PHYS_GRID_INIT error: opt", opt, "specified, ", &
              "but could not divide processes into pairs."
        endif
        call endrun()
     endif

endrun is just a rename of shr_sys_abort, which itself is just a rename
of shr_abort_abort. When endrun (or shr_abort_abort) is called without a
parameter it outputs the following string:

  ERROR: Unknown error submitted to shr_abort_abort.

This occurs for each process calling endrun.

When endrun is called in the second fashion, a meaningful message is written
to atm.log by masterproc, but then shr_abort_abort prints out npes-1 copies
of the "Unknown error" message to e3sm.log and one copy to atm.log. Unless
the user is familiar with this behavior, they may not think to look for
a "real" error message in one of the component logs.

It would be nice if a call to endrun without a parameter would not produce
any output, since there is already an explicit error being output. This would
require a change to shr_abort_abort and would affect the whole model, so
will require further investigation. This PR instead modifies endrun, a
CAM-specific routine, to instead pass the string

     "See atm.log for error description"

to the shr_sys_abort routine when endrun is called with no parameters.

Fixes #2498

[BFB]

### CODE REVIEW

**Comment by worleyph** [comment]
I dropped in an endrun call with a string parameter, and it worked as expected.

File: components/cam/src/utils/cam_abortutils.F90 [hunk 1]
```diff
@@ -1,11 +1,75 @@
...
+      else
+        call shr_sys_abort(string)
+      endif
+    else
+      if (present(rc)) then
+        call shr_sys_abort(cam_string,rc)
+      else
+        call shr_sys_abort(cam_string)
+      endif
+    endif
```
Comment (singhbalwinder) [inline components/cam/src/utils/cam_abortutils.F90]: I like the way you organized the code and that it is very clean! Could we re-organize the above if-statements in the following way? Unless I am missing something, it has the same logic but a little bit of less code (removed `parameter` from `cam_string` definition and rearranged if conditions). Also, code is okay in its current state if you don't feel like modifying it.

```
character(len=*) :: &
      cam_string = "See atm.log for error description" ! generic string
....
....
if (present(string)) cam_string = string

if (present(rc)) then
   call shr_sys_abort(ca_string,rc)
else
   call shr_sys_abort(cam_string)
endif
```
Everything else looks great!

**Comment by singhbalwinder** [comment]
> It looks to be an improvement over the current design

I also think that it is an improvement as it lets the user know where to look for the real error message. Sometimes users assume that `Unknown error` is a machine/nodes error and do not look for the real error in the logs.

File: components/cam/src/utils/cam_abortutils.F90 (hunk 1 above)
Comment (worleyph) [reply components/cam/src/utils/cam_abortutils.F90]: Looks correct (and much cleaner - thanks for putting in the effort). I'll give it a try and then push a new commit if it works.

Comment (worleyph) [reply components/cam/src/utils/cam_abortutils.F90]: If the string passed into the routine is longer than cam_string, will cam_string be lengthened automatically (wouldn't think so) or will the new string be truncated to fit into cam_string?

Since endrun is never called with an rc argument, I could leave this off as well. Since endrun is (now) equivalanced to shr_sys_abort, I added this in, but endrun was never defined with an rc argument in the past.  Any opinion on whether rc should be kept or dropped?

Comment (worleyph) [reply components/cam/src/utils/cam_abortutils.F90]: Nope:

PGF90-S-0089-Illegal use of symbol, cam_string, with character length = * (/autofs/nccs-svm1_home1/worley/E3SM/worleyph/cam/endrun_mod/E3SM/components/cam/\
src/utils/cam_abortutils.F90)
  0 inform,   0 warnings,   1 severes, 0 fatal for endrun

I can give the string a real length (e.g. shr_kind_cl). That should work. Any opinion about how long the string should be? 

The original implementation doesn't require a cap on the string length. Does this make it a better choice?

**Comment by worleyph** [comment]
@singhbalwinder , Changes made. Please re-review. Thanks.

**Comment by singhbalwinder** [comment]
Thanks @worleyph ! I will start integrating it.
